name: Build
on: [push]

jobs:
  build:
    name: Run TestCafe Tests
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 13.x    
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn e2e
      - name: Run visual tests
        env:
            PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: yarn visual-test
      - name: Generate Reports
        if: always()
        run: yarn reports
      - name: Archive test artifacts
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: reports

  sonarcloud:
    name: Run Sonar Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.sonar_key }}
