name: Basic TestCafe Workflow
on: [push]

jobs:
  build:
    name: Run TestCafe Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 13.x     
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn tests
      - name: Generate Reports
        run: yarn reports
      - name: Archive test artifacts
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: reports
    
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
      - uses: actions/checkout@v1
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.sonar_key }}